PRIVACY_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Privacy Policy – Daily Kids Activities</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 720px; margin: 0 auto; padding: 32px 20px; color: #1a1a1a; line-height: 1.7; }
    h1 { color: #FF6B35; }
    h2 { margin-top: 2em; }
    a { color: #FF6B35; }
    footer { margin-top: 3em; font-size: 0.85em; color: #888; }
  </style>
</head>
<body>
  <h1>Privacy Policy</h1>
  <p><strong>App:</strong> Daily Kids Activities<br>
  <strong>Developer:</strong> Yuliia Herman<br>
  <strong>Effective date:</strong> June 3, 2026</p>

  <h2>1. Information We Collect</h2>
  <p>We collect only what is necessary to provide the service:</p>
  <ul>
    <li><strong>Account data</strong> — your email address and password (stored as a secure hash).</li>
    <li><strong>Children's profiles</strong> — first name and age in months. No last names, photos, or sensitive identifiers are required.</li>
    <li><strong>Location</strong> — approximate city-level location used to fetch local weather. Location is requested only when you use the app and is never stored on our servers.</li>
    <li><strong>Activity history</strong> — activities you generate, save, or mark as favorites, linked to your account.</li>
  </ul>

  <h2>2. How We Use Your Information</h2>
  <ul>
    <li>Generate age-appropriate activity suggestions via AI (OpenAI API).</li>
    <li>Personalise suggestions based on children's ages and your preferences.</li>
    <li>Allow you to review your activity history and favourites.</li>
  </ul>
  <p>We do <strong>not</strong> sell, rent, or share your personal information with third parties for marketing purposes.</p>

  <h2>3. Third-Party Services</h2>
  <ul>
    <li><strong>OpenAI</strong> — activity content is generated by OpenAI's API. Children's names and personal details are <em>not</em> sent to OpenAI; only age ranges and activity preferences are included in prompts.</li>
    <li><strong>Open-Meteo</strong> — weather data fetched by city coordinates. No account data is shared.</li>
  </ul>

  <h2>4. Data Storage and Security</h2>
  <p>Your data is stored on secure servers hosted on Railway.app. Passwords are hashed using bcrypt and never stored in plain text. We use HTTPS for all data transmission.</p>

  <h2>5. Children's Privacy</h2>
  <p>Daily Kids Activities is designed for parents and caregivers. We do not knowingly collect personal information directly from children. Children's profile data (first name, age) is entered by the parent/guardian and is used solely to personalise activity recommendations.</p>

  <h2>6. Data Deletion</h2>
  <p>You can delete your account and all associated data at any time from the Profile screen inside the app. Deletion is permanent and irreversible.</p>

  <h2>7. Contact</h2>
  <p>Questions about this policy? Email us at <a href="mailto:childrendailyactivities@gmail.com">childrendailyactivities@gmail.com</a>.</p>

  <footer>
    <p>Last updated: June 3, 2026</p>
  </footer>
</body>
</html>"""

SUPPORT_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Support – Daily Kids Activities</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 720px; margin: 0 auto; padding: 32px 20px; color: #1a1a1a; line-height: 1.7; }
    h1 { color: #FF6B35; }
    h2 { margin-top: 2em; }
    a { color: #FF6B35; }
    footer { margin-top: 3em; font-size: 0.85em; color: #888; }
    .faq dt { font-weight: 600; margin-top: 1.2em; }
    .faq dd { margin-left: 0; }
  </style>
</head>
<body>
  <h1>Support</h1>
  <p><strong>Daily Kids Activities</strong> — personalised activity plans for your children, powered by AI.</p>
  <p>Need help? Email us at <a href="mailto:childrendailyactivities@gmail.com">childrendailyactivities@gmail.com</a> and we'll respond within 1–2 business days.</p>

  <h2>Frequently Asked Questions</h2>
  <dl class="faq">
    <dt>How do I add a child?</dt>
    <dd>Tap the Profile tab → "Add child". Enter your child's name and date of birth. You can add multiple children.</dd>

    <dt>How are activities generated?</dt>
    <dd>We use AI (powered by OpenAI) to create age-appropriate activity plans based on your child's age, the current weather, time of day, and any preferences you set.</dd>

    <dt>Can I save activities I like?</dt>
    <dd>Yes. Tap the heart icon on any activity card to add it to your favourites. You can view all saved activities in the History tab.</dd>

    <dt>What does "Mix with favourites" do?</dt>
    <dd>When you have saved favourite activities, enabling this toggle asks the AI to generate plans that blend new ideas with activities your child already enjoys.</dd>

    <dt>Why does the app ask for my location?</dt>
    <dd>Location is used to fetch local weather so the app can suggest outdoor vs. indoor activities appropriately. Location is never stored.</dd>

    <dt>How do I delete my account?</dt>
    <dd>Go to Profile → scroll to the bottom → "Delete account". This permanently deletes your account and all data.</dd>

    <dt>The app is not generating activities — what should I do?</dt>
    <dd>Check your internet connection. If the problem persists, contact us at the email below with a description of what happened.</dd>
  </dl>

  <h2>Contact</h2>
  <p>Email: <a href="mailto:childrendailyactivities@gmail.com">childrendailyactivities@gmail.com</a></p>

  <footer>
    <p>Daily Kids Activities &copy; 2026 Yuliia Herman</p>
  </footer>
</body>
</html>"""
